 
 


export const metadata = {
  title: "Home Page ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
        {children}
    </div>
  );
}
